# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: postgres
      POSTGRES_USER : dev
    ports:
      - 5102:5432